/**
 * Controlled demo provider for judging. Two independent providers
 * (Northwind, Atlas) serve company filings synchronously; Northwind also runs
 * an async report job that delivers by signed callback. Built on the
 * `pactProvider` SDK helper. Each pact can be armed in-process with a
 * misbehaviour so failure paths are reproducible on demand. Data is synthetic.
 */
import { createHash, randomBytes } from 'node:crypto'
import { Hono } from 'hono'
import type { Account } from 'viem'

import { digest } from '@pact/core'
import { pactProvider, type FetchLike, type PactContext, type PactProvider } from '@pact/tempo'

export type ProviderKey = 'northwind' | 'atlas'

export type Behavior =
  | 'normal'
  | 'incomplete'
  | 'malformed'
  | 'timeout'
  | 'wrong'
  | 'delayed'
  | 'duplicate'
  | 'replay'
  | 'forged'
  | 'http_error'
  | 'duplicate_callback'

type Signed = { body: string; headers: Record<string, string>; pactId: string }

export type DemoProviderOptions = {
  accounts: Record<ProviderKey, Account>
  forger: Account
  /** Used to POST async callbacks back to the gateway. */
  callbackFetch: FetchLike
  delayedMs?: number
  timeoutMs?: number
  reportDelayMs?: number
}

const TICKERS: Record<string, string> = {
  NVIDIA: 'NVDA',
  Apple: 'AAPL',
  Microsoft: 'MSFT',
  Tesla: 'TSLA',
  Alphabet: 'GOOGL',
  Amazon: 'AMZN',
  'Advanced Micro Devices': 'AMD',
}

const sleep = (ms: number, signal?: AbortSignal) =>
  new Promise<void>((resolve) => {
    const t = setTimeout(resolve, ms)
    signal?.addEventListener('abort', () => {
      clearTimeout(t)
      resolve()
    })
  })

function seeded(input: string) {
  let h = createHash('sha256').update(input).digest()
  let i = 0
  return () => {
    if (i + 4 > h.length) {
      h = createHash('sha256').update(h).digest()
      i = 0
    }
    const v = h.readUInt32BE(i) / 0xffffffff
    i += 4
    return v
  }
}

const tickerFor = (company: string) =>
  TICKERS[company] ?? (company.replace(/[^A-Za-z]/g, '').slice(0, 4).toUpperCase() || 'CO')

export function buildFilings(company: string, count: number) {
  const rand = seeded(`filings:${company}`)
  const ticker = tickerFor(company)
  const base = 5e9 + rand() * 40e9
  const latest = 2026 * 4 + 1 // 2026-Q2
  const filings = Array.from({ length: count }, (_, i) => {
    const idx = latest - i
    const year = Math.floor(idx / 4)
    const quarter = (idx % 4) + 1
    const filedYear = quarter === 4 ? year + 1 : year
    const filedMonth = quarter === 4 ? 2 : quarter * 3 + 1
    const form = quarter === 4 ? '10-K' : '10-Q'
    return {
      form,
      period: `${year}-Q${quarter}`,
      revenueUsd: Math.round(base * (1 - i * 0.04) * (0.95 + rand() * 0.1)),
      filedAt: `${filedYear}-${String(filedMonth).padStart(2, '0')}-${String(10 + Math.floor(rand() * 15)).padStart(2, '0')}`,
      source: `https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=${ticker}&type=${form}`,
    }
  })
  return { company, ticker, filings }
}

export function buildReport(market: string, sections: number) {
  const rand = seeded(`report:${market}`)
  const headings = ['Market size', 'Growth drivers', 'Competitive landscape', 'Regulation', 'Unit economics', 'Risks', 'Outlook']
  return {
    title: `${market}: market report`,
    market,
    generatedAt: new Date().toISOString(),
    sections: Array.from({ length: sections }, (_, i) => ({
      heading: headings[i % headings.length]! + (i >= headings.length ? ` (${Math.floor(i / headings.length) + 1})` : ''),
      body: `${headings[i % headings.length]} for ${market}: synthetic analysis paragraph ${i + 1} generated by the PACT demo provider.`,
      sourceCount: 2 + Math.floor(rand() * 6),
    })),
  }
}

export class DemoProvider {
  readonly app = new Hono()
  private readonly providers: Record<ProviderKey, PactProvider>
  private readonly armed = new Map<string, Behavior>()
  private readonly lastSigned = new Map<ProviderKey, Signed>()
  private readonly jobs = new Set<Promise<unknown>>()

  constructor(private readonly o: DemoProviderOptions) {
    this.providers = {
      northwind: pactProvider({ account: o.accounts.northwind, fetch: o.callbackFetch }),
      atlas: pactProvider({ account: o.accounts.atlas, fetch: o.callbackFetch }),
    }
    this.app.post('/:provider/filings', (c) => this.filings(c.req.param('provider') as ProviderKey, c.req.raw))
    this.app.post('/:provider/report', (c) => this.report(c.req.param('provider') as ProviderKey, c.req.raw))
    this.app.get('/', (c) =>
      c.json({
        providers: Object.entries(this.providers).map(([key, p]) => ({ key, address: p.address })),
        note: 'Demo provider. Data is synthetic. Behaviour is armed per pact by the PACT Chaos Lab.',
      }),
    )
  }

  /** In-process only: never exposed over HTTP, so outsiders cannot steer provider behaviour. */
  arm(pactId: string, behavior: Behavior) {
    this.armed.set(pactId, behavior)
  }

  async idle() {
    while (this.jobs.size) await Promise.allSettled([...this.jobs])
  }

  private take(pactId: string): Behavior {
    const b = this.armed.get(pactId) ?? 'normal'
    this.armed.delete(pactId)
    return b
  }

  private async signed(provider: PactProvider, ctx: PactContext, body: string, signer?: Account): Promise<Signed> {
    return { body, headers: await provider.attest(ctx, body, signer), pactId: ctx.pactId }
  }

  private send(s: Signed, status = 200) {
    return new Response(s.body, { status, headers: { 'content-type': 'application/json; charset=utf-8', ...s.headers } })
  }

  private async filings(key: ProviderKey, req: Request) {
    const provider = this.providers[key]
    if (!provider) return Response.json({ error: 'unknown provider' }, { status: 404 })
    const ctx = provider.context(req)
    const input = (await req.json().catch(() => null)) as { request?: { company?: unknown; count?: unknown } } | null
    const company = typeof input?.request?.company === 'string' ? input.request.company.slice(0, 80) : ''
    const count = Math.min(Math.max(Number(input?.request?.count) || 4, 1), 12)
    if (!ctx || !company) return Response.json({ error: 'missing pact headers or company' }, { status: 400 })

    const behavior = this.take(ctx.pactId)
    const good = () => JSON.stringify(buildFilings(company, count))

    switch (behavior) {
      case 'timeout':
        await sleep(this.o.timeoutMs ?? 30_000, req.signal)
        return this.send(await this.signed(provider, ctx, good()))
      case 'delayed':
        await sleep(this.o.delayedMs ?? 5_000, req.signal)
        return this.send(await this.signed(provider, ctx, good()))
      case 'incomplete': {
        const r = buildFilings(company, count)
        r.filings = r.filings.slice(0, Math.max(1, Math.floor(count / 2)))
        return this.send(await this.signed(provider, ctx, JSON.stringify(r)))
      }
      case 'malformed': {
        const text = good()
        return this.send(await this.signed(provider, ctx, text.slice(0, Math.floor(text.length * 0.6))))
      }
      case 'wrong': {
        const other = company === 'Advanced Micro Devices' ? 'NVIDIA' : 'Advanced Micro Devices'
        return this.send(await this.signed(provider, ctx, JSON.stringify(buildFilings(other, count))))
      }
      case 'duplicate': {
        const r = buildFilings(company, count)
        if (r.filings.length > 1) r.filings[r.filings.length - 1] = r.filings[0]!
        return this.send(await this.signed(provider, ctx, JSON.stringify(r)))
      }
      case 'replay': {
        let prior = this.lastSigned.get(key)
        if (!prior || prior.pactId === ctx.pactId) {
          const earlier: PactContext = {
            pactId: `pact_${randomBytes(10).toString('hex')}`,
            requestDigest: digest({ serviceId: 'earlier', request: { company, count } }),
            deadline: null,
            callbackUrl: null,
          }
          prior = await this.signed(provider, earlier, good())
        }
        return this.send(prior)
      }
      case 'forged':
        return this.send(await this.signed(provider, ctx, good(), this.o.forger))
      case 'http_error':
        return Response.json({ error: 'upstream data vendor unavailable' }, { status: 503 })
      default: {
        const s = await this.signed(provider, ctx, good())
        this.lastSigned.set(key, s)
        return this.send(s)
      }
    }
  }

  private async report(key: ProviderKey, req: Request) {
    const provider = this.providers[key]
    if (!provider) return Response.json({ error: 'unknown provider' }, { status: 404 })
    const ctx = provider.context(req)
    const input = (await req.json().catch(() => null)) as { request?: { market?: unknown; sections?: unknown } } | null
    const market = typeof input?.request?.market === 'string' ? input.request.market.slice(0, 80) : ''
    const sections = Math.min(Math.max(Number(input?.request?.sections) || 5, 1), 20)
    if (!ctx || !ctx.callbackUrl || !market)
      return Response.json({ error: 'missing pact headers, callback or market' }, { status: 400 })

    const behavior = this.take(ctx.pactId)
    const jobId = `job_${randomBytes(6).toString('hex')}`
    const job = (async () => {
      await sleep(this.o.reportDelayMs ?? 6_000)
      if (behavior === 'timeout') return
      const report = buildReport(market, behavior === 'incomplete' ? Math.max(1, sections - 2) : sections)
      let body = JSON.stringify(report)
      if (behavior === 'malformed') body = body.slice(0, Math.floor(body.length * 0.6))
      const s = await this.signed(provider, ctx, body, behavior === 'forged' ? this.o.forger : undefined)
      const post = () =>
        this.o
          .callbackFetch(ctx.callbackUrl!, {
            method: 'POST',
            headers: { 'content-type': 'application/json; charset=utf-8', ...s.headers },
            body: s.body,
          })
          .catch(() => null)
      await post()
      if (behavior === 'duplicate_callback') await post()
    })()
    this.jobs.add(job)
    void job.finally(() => this.jobs.delete(job))
    return Response.json({ jobId, status: 'accepted' }, { status: 202 })
  }
}
